// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_MsgId = 1,
  Message_FieldNumber_MsgSn = 2,
  Message_FieldNumber_Sercte = 3,
  Message_FieldNumber_SendId = 4,
  Message_FieldNumber_ReciveId = 5,
  Message_FieldNumber_TerminalType = 6,
  Message_FieldNumber_MsgType = 7,
  Message_FieldNumber_Token = 8,
  Message_FieldNumber_TimeStamp = 9,
  Message_FieldNumber_MsgContent = 10,
  Message_FieldNumber_ReplyMsg = 11,
  Message_FieldNumber_GroupMessage = 12,
  Message_FieldNumber_GroupId = 13,
};

@interface Message : GPBMessage

/** 消息类型 */
@property(nonatomic, readwrite) int32_t msgId;

/** 消息时间戳 */
@property(nonatomic, readwrite) uint64_t msgSn;

/** 是否加密 */
@property(nonatomic, readwrite) BOOL sercte;

/** 发送者ID */
@property(nonatomic, readwrite) uint32_t sendId;

/** 接收者ID */
@property(nonatomic, readwrite) uint32_t reciveId;

/** 终端类型 */
@property(nonatomic, readwrite) uint32_t terminalType;

/** 消息正文类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

/** 是否群消息 */
@property(nonatomic, readwrite) BOOL groupMessage;

/** 群ID */
@property(nonatomic, readwrite) uint32_t groupId;

/** 0x8001 */
@property(nonatomic, readwrite) int32_t replyMsg;

/** 0x0003 0x0004 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) uint64_t timeStamp;

/** 0x8004 8003 0005 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *msgContent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
